<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'alpha3' => 'AFG', 'flag_emoji' => '🇦🇫'],
            ['name' => 'Åland Islands', 'code' => 'AX', 'alpha3' => 'ALA', 'flag_emoji' => '🇦🇽'],
            ['name' => 'Albania', 'code' => 'AL', 'alpha3' => 'ALB', 'flag_emoji' => '🇦🇱'],
            ['name' => 'Algeria', 'code' => 'DZ', 'alpha3' => 'DZA', 'flag_emoji' => '🇩🇿'],
            ['name' => 'American Samoa', 'code' => 'AS', 'alpha3' => 'ASM', 'flag_emoji' => '🇦🇸'],
            ['name' => 'Andorra', 'code' => 'AD', 'alpha3' => 'AND', 'flag_emoji' => '🇦🇩'],
            ['name' => 'Angola', 'code' => 'AO', 'alpha3' => 'AGO', 'flag_emoji' => '🇦🇴'],
            ['name' => 'Anguilla', 'code' => 'AI', 'alpha3' => 'AIA', 'flag_emoji' => '🇦🇮'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'alpha3' => 'ATA', 'flag_emoji' => '🇦🇶'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'alpha3' => 'ATG', 'flag_emoji' => '🇦🇬'],
            ['name' => 'Argentina', 'code' => 'AR', 'alpha3' => 'ARG', 'flag_emoji' => '🇦🇷'],
            ['name' => 'Armenia', 'code' => 'AM', 'alpha3' => 'ARM', 'flag_emoji' => '🇦🇲'],
            ['name' => 'Aruba', 'code' => 'AW', 'alpha3' => 'ABW', 'flag_emoji' => '🇦🇼'],
            ['name' => 'Australia', 'code' => 'AU', 'alpha3' => 'AUS', 'flag_emoji' => '🇦🇺'],
            ['name' => 'Austria', 'code' => 'AT', 'alpha3' => 'AUT', 'flag_emoji' => '🇦🇹'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'alpha3' => 'AZE', 'flag_emoji' => '🇦🇿'],
            ['name' => 'Bahamas', 'code' => 'BS', 'alpha3' => 'BHS', 'flag_emoji' => '🇧🇸'],
            ['name' => 'Bahrain', 'code' => 'BH', 'alpha3' => 'BHR', 'flag_emoji' => '🇧🇭'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'alpha3' => 'BGD', 'flag_emoji' => '🇧🇩'],
            ['name' => 'Barbados', 'code' => 'BB', 'alpha3' => 'BRB', 'flag_emoji' => '🇧🇧'],
            ['name' => 'Belarus', 'code' => 'BY', 'alpha3' => 'BLR', 'flag_emoji' => '🇧🇾'],
            ['name' => 'Belgium', 'code' => 'BE', 'alpha3' => 'BEL', 'flag_emoji' => '🇧🇪'],
            ['name' => 'Belize', 'code' => 'BZ', 'alpha3' => 'BLZ', 'flag_emoji' => '🇧🇿'],
            ['name' => 'Benin', 'code' => 'BJ', 'alpha3' => 'BEN', 'flag_emoji' => '🇧🇯'],
            ['name' => 'Bermuda', 'code' => 'BM', 'alpha3' => 'BMU', 'flag_emoji' => '🇧🇲'],
            ['name' => 'Bhutan', 'code' => 'BT', 'alpha3' => 'BTN', 'flag_emoji' => '🇧🇹'],
            ['name' => 'Bolivia', 'code' => 'BO', 'alpha3' => 'BOL', 'flag_emoji' => '🇧🇴'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ', 'alpha3' => 'BES', 'flag_emoji' => '🇧🇶'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'alpha3' => 'BIH', 'flag_emoji' => '🇧🇦'],
            ['name' => 'Botswana', 'code' => 'BW', 'alpha3' => 'BWA', 'flag_emoji' => '🇧🇼'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'alpha3' => 'BVT', 'flag_emoji' => '🇧🇻'],
            ['name' => 'Brazil', 'code' => 'BR', 'alpha3' => 'BRA', 'flag_emoji' => '🇧🇷'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'alpha3' => 'IOT', 'flag_emoji' => '🇮🇴'],
            ['name' => 'British Virgin Islands', 'code' => 'VG', 'alpha3' => 'VGB', 'flag_emoji' => '🇻🇬'],
            ['name' => 'Brunei', 'code' => 'BN', 'alpha3' => 'BRN', 'flag_emoji' => '🇧🇳'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'alpha3' => 'BGR', 'flag_emoji' => '🇧🇬'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'alpha3' => 'BFA', 'flag_emoji' => '🇧🇫'],
            ['name' => 'Burundi', 'code' => 'BI', 'alpha3' => 'BDI', 'flag_emoji' => '🇧🇮'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI', 'alpha3' => 'CIV', 'flag_emoji' => '🇨🇮'],
            ['name' => 'Cabo Verde / Cape Verde', 'code' => 'CV', 'alpha3' => 'CPV', 'flag_emoji' => '🇨🇻'],
            ['name' => 'Cambodia', 'code' => 'KH', 'alpha3' => 'KHM', 'flag_emoji' => '🇰🇭'],
            ['name' => 'Cameroon', 'code' => 'CM', 'alpha3' => 'CMR', 'flag_emoji' => '🇨🇲'],
            ['name' => 'Canada', 'code' => 'CA', 'alpha3' => 'CAN', 'flag_emoji' => '🇨🇦'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'alpha3' => 'CYM', 'flag_emoji' => '🇰🇾'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'alpha3' => 'CAF', 'flag_emoji' => '🇨🇫'],
            ['name' => 'Chad', 'code' => 'TD', 'alpha3' => 'TCD', 'flag_emoji' => '🇹🇩'],
            ['name' => 'Chile', 'code' => 'CL', 'alpha3' => 'CHL', 'flag_emoji' => '🇨🇱'],
            ['name' => 'China', 'code' => 'CN', 'alpha3' => 'CHN', 'flag_emoji' => '🇨🇳'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'alpha3' => 'CXR', 'flag_emoji' => '🇨🇽'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'alpha3' => 'CCK', 'flag_emoji' => '🇨🇨'],
            ['name' => 'Colombia', 'code' => 'CO', 'alpha3' => 'COL', 'flag_emoji' => '🇨🇴'],
            ['name' => 'Comoros', 'code' => 'KM', 'alpha3' => 'COM', 'flag_emoji' => '🇰🇲'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'alpha3' => 'COK', 'flag_emoji' => '🇨🇰'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'alpha3' => 'CRI', 'flag_emoji' => '🇨🇷'],
            ['name' => 'Croatia', 'code' => 'HR', 'alpha3' => 'HRV', 'flag_emoji' => '🇭🇷'],
            ['name' => 'Cuba', 'code' => 'CU', 'alpha3' => 'CUB', 'flag_emoji' => '🇨🇺'],
            ['name' => 'Curaçao', 'code' => 'CW', 'alpha3' => 'CUW', 'flag_emoji' => '🇨🇼'],
            ['name' => 'Cyprus', 'code' => 'CY', 'alpha3' => 'CYP', 'flag_emoji' => '🇨🇾'],
            ['name' => 'Czechia', 'code' => 'CZ', 'alpha3' => 'CZE', 'flag_emoji' => '🇨🇿'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'CD', 'alpha3' => 'COD', 'flag_emoji' => '🇨🇩'],
            ['name' => 'Denmark', 'code' => 'DK', 'alpha3' => 'DNK', 'flag_emoji' => '🇩🇰'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'alpha3' => 'DJI', 'flag_emoji' => '🇩🇯'],
            ['name' => 'Dominica', 'code' => 'DM', 'alpha3' => 'DMA', 'flag_emoji' => '🇩🇲'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'alpha3' => 'DOM', 'flag_emoji' => '🇩🇴'],
            ['name' => 'Ecuador', 'code' => 'EC', 'alpha3' => 'ECU', 'flag_emoji' => '🇪🇨'],
            ['name' => 'Egypt', 'code' => 'EG', 'alpha3' => 'EGY', 'flag_emoji' => '🇪🇬'],
            ['name' => 'El Salvador', 'code' => 'SV', 'alpha3' => 'SLV', 'flag_emoji' => '🇸🇻'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'alpha3' => 'GNQ', 'flag_emoji' => '🇬🇶'],
            ['name' => 'Eritrea', 'code' => 'ER', 'alpha3' => 'ERI', 'flag_emoji' => '🇪🇷'],
            ['name' => 'Estonia', 'code' => 'EE', 'alpha3' => 'EST', 'flag_emoji' => '🇪🇪'],
            ['name' => 'Eswatini', 'code' => 'SZ', 'alpha3' => 'SWZ', 'flag_emoji' => '🇸🇿'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'alpha3' => 'ETH', 'flag_emoji' => '🇪🇹'],
            ['name' => 'European Union', 'code' => 'EU', 'alpha3' => 'EUR', 'flag_emoji' => '🇪🇺'],
            ['name' => 'Falkland Islands', 'code' => 'FK', 'alpha3' => 'FLK', 'flag_emoji' => '🇫🇰'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'alpha3' => 'FRO', 'flag_emoji' => '🇫🇴'],
            ['name' => 'Fiji', 'code' => 'FJ', 'alpha3' => 'FJI', 'flag_emoji' => '🇫🇯'],
            ['name' => 'Finland', 'code' => 'FI', 'alpha3' => 'FIN', 'flag_emoji' => '🇫🇮'],
            ['name' => 'France', 'code' => 'FR', 'alpha3' => 'FRA', 'flag_emoji' => '🇫🇷'],
            ['name' => 'French Guiana', 'code' => 'GF', 'alpha3' => 'GUF', 'flag_emoji' => '🇬🇫'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'alpha3' => 'PYF', 'flag_emoji' => '🇵🇫'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'alpha3' => 'ATF', 'flag_emoji' => '🇹🇫'],
            ['name' => 'Gabon', 'code' => 'GA', 'alpha3' => 'GAB', 'flag_emoji' => '🇬🇦'],
            ['name' => 'Gambia', 'code' => 'GM', 'alpha3' => 'GMB', 'flag_emoji' => '🇬🇲'],
            ['name' => 'Georgia', 'code' => 'GE', 'alpha3' => 'GEO', 'flag_emoji' => '🇬🇪'],
            ['name' => 'Germany', 'code' => 'DE', 'alpha3' => 'DEU', 'flag_emoji' => '🇩🇪'],
            ['name' => 'Ghana', 'code' => 'GH', 'alpha3' => 'GHA', 'flag_emoji' => '🇬🇭'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'alpha3' => 'GIB', 'flag_emoji' => '🇬🇮'],
            ['name' => 'Greece', 'code' => 'GR', 'alpha3' => 'GRC', 'flag_emoji' => '🇬🇷'],
            ['name' => 'Greenland', 'code' => 'GL', 'alpha3' => 'GRL', 'flag_emoji' => '🇬🇱'],
            ['name' => 'Grenada', 'code' => 'GD', 'alpha3' => 'GRD', 'flag_emoji' => '🇬🇩'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'alpha3' => 'GLP', 'flag_emoji' => '🇬🇵'],
            ['name' => 'Guam', 'code' => 'GU', 'alpha3' => 'GUM', 'flag_emoji' => '🇬🇺'],
            ['name' => 'Guatemala', 'code' => 'GT', 'alpha3' => 'GTM', 'flag_emoji' => '🇬🇹'],
            ['name' => 'Guernsey', 'code' => 'GG', 'alpha3' => 'GGY', 'flag_emoji' => '🇬🇬'],
            ['name' => 'Guinea', 'code' => 'GN', 'alpha3' => 'GIN', 'flag_emoji' => '🇬🇳'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'alpha3' => 'GNB', 'flag_emoji' => '🇬🇼'],
            ['name' => 'Guyana', 'code' => 'GY', 'alpha3' => 'GUY', 'flag_emoji' => '🇬🇾'],
            ['name' => 'Haiti', 'code' => 'HT', 'alpha3' => 'HTI', 'flag_emoji' => '🇭🇹'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM', 'alpha3' => 'HMD', 'flag_emoji' => '🇭🇲'],
            ['name' => 'Honduras', 'code' => 'HN', 'alpha3' => 'HND', 'flag_emoji' => '🇭🇳'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'alpha3' => 'HKG', 'flag_emoji' => '🇭🇰'],
            ['name' => 'Hungary', 'code' => 'HU', 'alpha3' => 'HUN', 'flag_emoji' => '🇭🇺'],
            ['name' => 'Iceland', 'code' => 'IS', 'alpha3' => 'ISL', 'flag_emoji' => '🇮🇸'],
            ['name' => 'India', 'code' => 'IN', 'alpha3' => 'IND', 'flag_emoji' => '🇮🇳'],
            ['name' => 'Indonesia', 'code' => 'ID', 'alpha3' => 'IDN', 'flag_emoji' => '🇮🇩'],
            ['name' => 'Iran', 'code' => 'IR', 'alpha3' => 'IRN', 'flag_emoji' => '🇮🇷'],
            ['name' => 'Iraq', 'code' => 'IQ', 'alpha3' => 'IRQ', 'flag_emoji' => '🇮🇶'],
            ['name' => 'Ireland', 'code' => 'IE', 'alpha3' => 'IRL', 'flag_emoji' => '🇮🇪'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'alpha3' => 'IMN', 'flag_emoji' => '🇮🇲'],
            ['name' => 'Israel', 'code' => 'IL', 'alpha3' => 'ISR', 'flag_emoji' => '🇮🇱'],
            ['name' => 'Italy', 'code' => 'IT', 'alpha3' => 'ITA', 'flag_emoji' => '🇮🇹'],
            ['name' => 'Jamaica', 'code' => 'JM', 'alpha3' => 'JAM', 'flag_emoji' => '🇯🇲'],
            ['name' => 'Japan', 'code' => 'JP', 'alpha3' => 'JPN', 'flag_emoji' => '🇯🇵'],
            ['name' => 'Jersey', 'code' => 'JE', 'alpha3' => 'JEY', 'flag_emoji' => '🇯🇪'],
            ['name' => 'Jordan', 'code' => 'JO', 'alpha3' => 'JOR', 'flag_emoji' => '🇯🇴'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'alpha3' => 'KAZ', 'flag_emoji' => '🇰🇿'],
            ['name' => 'Kenya', 'code' => 'KE', 'alpha3' => 'KEN', 'flag_emoji' => '🇰🇪'],
            ['name' => 'Kiribati', 'code' => 'KI', 'alpha3' => 'KIR', 'flag_emoji' => '🇰🇮'],
            ['name' => 'Kuwait', 'code' => 'KW', 'alpha3' => 'KWT', 'flag_emoji' => '🇰🇼'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'alpha3' => 'KGZ', 'flag_emoji' => '🇰🇬'],
            ['name' => 'Laos', 'code' => 'LA', 'alpha3' => 'LAO', 'flag_emoji' => '🇱🇦'],
            ['name' => 'Latvia', 'code' => 'LV', 'alpha3' => 'LVA', 'flag_emoji' => '🇱🇻'],
            ['name' => 'Lebanon', 'code' => 'LB', 'alpha3' => 'LBN', 'flag_emoji' => '🇱🇧'],
            ['name' => 'Lesotho', 'code' => 'LS', 'alpha3' => 'LSO', 'flag_emoji' => '🇱🇸'],
            ['name' => 'Liberia', 'code' => 'LR', 'alpha3' => 'LBR', 'flag_emoji' => '🇱🇷'],
            ['name' => 'Libya', 'code' => 'LY', 'alpha3' => 'LBY', 'flag_emoji' => '🇱🇾'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'alpha3' => 'LIE', 'flag_emoji' => '🇱🇮'],
            ['name' => 'Lithuania', 'code' => 'LT', 'alpha3' => 'LTU', 'flag_emoji' => '🇱🇹'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'alpha3' => 'LUX', 'flag_emoji' => '🇱🇺'],
            ['name' => 'Macao', 'code' => 'MO', 'alpha3' => 'MAC', 'flag_emoji' => '🇲🇴'],
            ['name' => 'Madagascar', 'code' => 'MG', 'alpha3' => 'MDG', 'flag_emoji' => '🇲🇬'],
            ['name' => 'Malawi', 'code' => 'MW', 'alpha3' => 'MWI', 'flag_emoji' => '🇲🇼'],
            ['name' => 'Malaysia', 'code' => 'MY', 'alpha3' => 'MYS', 'flag_emoji' => '🇲🇾'],
            ['name' => 'Maldives', 'code' => 'MV', 'alpha3' => 'MDV', 'flag_emoji' => '🇲🇻'],
            ['name' => 'Mali', 'code' => 'ML', 'alpha3' => 'MLI', 'flag_emoji' => '🇲🇱'],
            ['name' => 'Malta', 'code' => 'MT', 'alpha3' => 'MLT', 'flag_emoji' => '🇲🇹'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'alpha3' => 'MHL', 'flag_emoji' => '🇲🇭'],
            ['name' => 'Martinique', 'code' => 'MQ', 'alpha3' => 'MTQ', 'flag_emoji' => '🇲🇶'],
            ['name' => 'Mauritania', 'code' => 'MR', 'alpha3' => 'MRT', 'flag_emoji' => '🇲🇷'],
            ['name' => 'Mauritius', 'code' => 'MU', 'alpha3' => 'MUS', 'flag_emoji' => '🇲🇺'],
            ['name' => 'Mayotte', 'code' => 'YT', 'alpha3' => 'MYT', 'flag_emoji' => '🇾🇹'],
            ['name' => 'Mexico', 'code' => 'MX', 'alpha3' => 'MEX', 'flag_emoji' => '🇲🇽'],
            ['name' => 'Micronesia', 'code' => 'FM', 'alpha3' => 'FSM', 'flag_emoji' => '🇫🇲'],
            ['name' => 'Moldova', 'code' => 'MD', 'alpha3' => 'MDA', 'flag_emoji' => '🇲🇩'],
            ['name' => 'Monaco', 'code' => 'MC', 'alpha3' => 'MCO', 'flag_emoji' => '🇲🇨'],
            ['name' => 'Mongolia', 'code' => 'MN', 'alpha3' => 'MNG', 'flag_emoji' => '🇲🇳'],
            ['name' => 'Montenegro', 'code' => 'ME', 'alpha3' => 'MNE', 'flag_emoji' => '🇲🇪'],
            ['name' => 'Montserrat', 'code' => 'MS', 'alpha3' => 'MSR', 'flag_emoji' => '🇲🇸'],
            ['name' => 'Morocco', 'code' => 'MA', 'alpha3' => 'MAR', 'flag_emoji' => '🇲🇦'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'alpha3' => 'MOZ', 'flag_emoji' => '🇲🇿'],
            ['name' => 'Myanmar', 'code' => 'MM', 'alpha3' => 'MMR', 'flag_emoji' => '🇲🇲'],
            ['name' => 'Namibia', 'code' => 'NA', 'alpha3' => 'NAM', 'flag_emoji' => '🇳🇦'],
            ['name' => 'Nauru', 'code' => 'NR', 'alpha3' => 'NRU', 'flag_emoji' => '🇳🇷'],
            ['name' => 'Nepal', 'code' => 'NP', 'alpha3' => 'NPL', 'flag_emoji' => '🇳🇵'],
            ['name' => 'Netherlands', 'code' => 'NL', 'alpha3' => 'NLD', 'flag_emoji' => '🇳🇱'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'alpha3' => 'NCL', 'flag_emoji' => '🇳🇨'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'alpha3' => 'NZL', 'flag_emoji' => '🇳🇿'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'alpha3' => 'NIC', 'flag_emoji' => '🇳🇮'],
            ['name' => 'Niger', 'code' => 'NE', 'alpha3' => 'NER', 'flag_emoji' => '🇳🇪'],
            ['name' => 'Nigeria', 'code' => 'NG', 'alpha3' => 'NGA', 'flag_emoji' => '🇳🇬'],
            ['name' => 'Niue', 'code' => 'NU', 'alpha3' => 'NIU', 'flag_emoji' => '🇳🇺'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'alpha3' => 'NFK', 'flag_emoji' => '🇳🇫'],
            ['name' => 'North Korea', 'code' => 'KP', 'alpha3' => 'PRK', 'flag_emoji' => '🇰🇵'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'alpha3' => 'MKD', 'flag_emoji' => '🇲🇰'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'alpha3' => 'MNP', 'flag_emoji' => '🇲🇵'],
            ['name' => 'Norway', 'code' => 'NO', 'alpha3' => 'NOR', 'flag_emoji' => '🇳🇴'],
            ['name' => 'Oman', 'code' => 'OM', 'alpha3' => 'OMN', 'flag_emoji' => '🇴🇲'],
            ['name' => 'Pakistan', 'code' => 'PK', 'alpha3' => 'PAK', 'flag_emoji' => '🇵🇰'],
            ['name' => 'Palau', 'code' => 'PW', 'alpha3' => 'PLW', 'flag_emoji' => '🇵🇼'],
            ['name' => 'Palestine', 'code' => 'PS', 'alpha3' => 'PSE', 'flag_emoji' => '🇵🇸'],
            ['name' => 'Panama', 'code' => 'PA', 'alpha3' => 'PAN', 'flag_emoji' => '🇵🇦'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'alpha3' => 'PNG', 'flag_emoji' => '🇵🇬'],
            ['name' => 'Paraguay', 'code' => 'PY', 'alpha3' => 'PRY', 'flag_emoji' => '🇵🇾'],
            ['name' => 'Peru', 'code' => 'PE', 'alpha3' => 'PER', 'flag_emoji' => '🇵🇪'],
            ['name' => 'Philippines', 'code' => 'PH', 'alpha3' => 'PHL', 'flag_emoji' => '🇵🇭'],
            ['name' => 'Pitcairn Islands', 'code' => 'PN', 'alpha3' => 'PCN', 'flag_emoji' => '🇵🇳'],
            ['name' => 'Poland', 'code' => 'PL', 'alpha3' => 'POL', 'flag_emoji' => '🇵🇱'],
            ['name' => 'Portugal', 'code' => 'PT', 'alpha3' => 'PRT', 'flag_emoji' => '🇵🇹'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'alpha3' => 'PRI', 'flag_emoji' => '🇵🇷'],
            ['name' => 'Qatar', 'code' => 'QA', 'alpha3' => 'QAT', 'flag_emoji' => '🇶🇦'],
            ['name' => 'Republic of the Congo', 'code' => 'CG', 'alpha3' => 'COG', 'flag_emoji' => '🇨🇬'],
            ['name' => 'Réunion', 'code' => 'RE', 'alpha3' => 'REU', 'flag_emoji' => '🇷🇪'],
            ['name' => 'Romania', 'code' => 'RO', 'alpha3' => 'ROU', 'flag_emoji' => '🇷🇴'],
            ['name' => 'Russia', 'code' => 'RU', 'alpha3' => 'RUS', 'flag_emoji' => '🇷🇺'],
            ['name' => 'Rwanda', 'code' => 'RW', 'alpha3' => 'RWA', 'flag_emoji' => '🇷🇼'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'alpha3' => 'BLM', 'flag_emoji' => '🇧🇱'],
            ['name' => 'Saint Helena', 'code' => 'SH', 'alpha3' => 'SHN', 'flag_emoji' => '🇸🇭'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'alpha3' => 'KNA', 'flag_emoji' => '🇰🇳'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'alpha3' => 'LCA', 'flag_emoji' => '🇱🇨'],
            ['name' => 'Saint Martin', 'code' => 'MF', 'alpha3' => 'MAF', 'flag_emoji' => '🇲🇫'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'alpha3' => 'SPM', 'flag_emoji' => '🇵🇲'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'alpha3' => 'VCT', 'flag_emoji' => '🇻🇨'],
            ['name' => 'Samoa', 'code' => 'WS', 'alpha3' => 'WSM', 'flag_emoji' => '🇼🇸'],
            ['name' => 'San Marino', 'code' => 'SM', 'alpha3' => 'SMR', 'flag_emoji' => '🇸🇲'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'alpha3' => 'STP', 'flag_emoji' => '🇸🇹'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'alpha3' => 'SAU', 'flag_emoji' => '🇸🇦'],
            ['name' => 'Senegal', 'code' => 'SN', 'alpha3' => 'SEN', 'flag_emoji' => '🇸🇳'],
            ['name' => 'Serbia', 'code' => 'RS', 'alpha3' => 'SRB', 'flag_emoji' => '🇷🇸'],
            ['name' => 'Seychelles', 'code' => 'SC', 'alpha3' => 'SYC', 'flag_emoji' => '🇸🇨'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'alpha3' => 'SLE', 'flag_emoji' => '🇸🇱'],
            ['name' => 'Singapore', 'code' => 'SG', 'alpha3' => 'SGP', 'flag_emoji' => '🇸🇬'],
            ['name' => 'Sint Maarten', 'code' => 'SX', 'alpha3' => 'SXM', 'flag_emoji' => '🇸🇽'],
            ['name' => 'Slovakia', 'code' => 'SK', 'alpha3' => 'SVK', 'flag_emoji' => '🇸🇰'],
            ['name' => 'Slovenia', 'code' => 'SI', 'alpha3' => 'SVN', 'flag_emoji' => '🇸🇮'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'alpha3' => 'SLB', 'flag_emoji' => '🇸🇧'],
            ['name' => 'Somalia', 'code' => 'SO', 'alpha3' => 'SOM', 'flag_emoji' => '🇸🇴'],
            ['name' => 'South Africa', 'code' => 'ZA', 'alpha3' => 'ZAF', 'flag_emoji' => '🇿🇦'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'alpha3' => 'SGS', 'flag_emoji' => '🇬🇸'],
            ['name' => 'South Korea', 'code' => 'KR', 'alpha3' => 'KOR', 'flag_emoji' => '🇰🇷'],
            ['name' => 'South Sudan', 'code' => 'SS', 'alpha3' => 'SSD', 'flag_emoji' => '🇸🇸'],
            ['name' => 'Spain', 'code' => 'ES', 'alpha3' => 'ESP', 'flag_emoji' => '🇪🇸'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'alpha3' => 'LKA', 'flag_emoji' => '🇱🇰'],
            ['name' => 'Sudan', 'code' => 'SD', 'alpha3' => 'SDN', 'flag_emoji' => '🇸🇩'],
            ['name' => 'Suriname', 'code' => 'SR', 'alpha3' => 'SUR', 'flag_emoji' => '🇸🇷'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'alpha3' => 'SJM', 'flag_emoji' => '🇸🇯'],
            ['name' => 'Sweden', 'code' => 'SE', 'alpha3' => 'SWE', 'flag_emoji' => '🇸🇪'],
            ['name' => 'Switzerland', 'code' => 'CH', 'alpha3' => 'CHE', 'flag_emoji' => '🇨🇭'],
            ['name' => 'Syria', 'code' => 'SY', 'alpha3' => 'SYR', 'flag_emoji' => '🇸🇾'],
            ['name' => 'Taiwan', 'code' => 'TW', 'alpha3' => 'TWN', 'flag_emoji' => '🇹🇼'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'alpha3' => 'TJK', 'flag_emoji' => '🇹🇯'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'alpha3' => 'TZA', 'flag_emoji' => '🇹🇿'],
            ['name' => 'Thailand', 'code' => 'TH', 'alpha3' => 'THA', 'flag_emoji' => '🇹🇭'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'alpha3' => 'TLS', 'flag_emoji' => '🇹🇱'],
            ['name' => 'Togo', 'code' => 'TG', 'alpha3' => 'TGO', 'flag_emoji' => '🇹🇬'],
            ['name' => 'Tokelau', 'code' => 'TK', 'alpha3' => 'TKL', 'flag_emoji' => '🇹🇰'],
            ['name' => 'Tonga', 'code' => 'TO', 'alpha3' => 'TON', 'flag_emoji' => '🇹🇴'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'alpha3' => 'TTO', 'flag_emoji' => '🇹🇹'],
            ['name' => 'Tunisia', 'code' => 'TN', 'alpha3' => 'TUN', 'flag_emoji' => '🇹🇳'],
            ['name' => 'Turkey', 'code' => 'TR', 'alpha3' => 'TUR', 'flag_emoji' => '🇹🇷'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'alpha3' => 'TKM', 'flag_emoji' => '🇹🇲'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'alpha3' => 'TUV', 'flag_emoji' => '🇹🇻'],
            ['name' => 'Uganda', 'code' => 'UG', 'alpha3' => 'UGA', 'flag_emoji' => '🇺🇬'],
            ['name' => 'Ukraine', 'code' => 'UA', 'alpha3' => 'UKR', 'flag_emoji' => '🇺🇦'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'alpha3' => 'ARE', 'flag_emoji' => '🇦🇪'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'alpha3' => 'GBR', 'flag_emoji' => '🇬🇧'],
            ['name' => 'United States', 'code' => 'US', 'alpha3' => 'USA', 'flag_emoji' => '🇺🇸'],
            ['name' => 'Uruguay', 'code' => 'UY', 'alpha3' => 'URY', 'flag_emoji' => '🇺🇾'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'alpha3' => 'UZB', 'flag_emoji' => '🇺🇿'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'alpha3' => 'VUT', 'flag_emoji' => '🇻🇺'],
            ['name' => 'Vatican City', 'code' => 'VA', 'alpha3' => 'VAT', 'flag_emoji' => '🇻🇦'],
            ['name' => 'Venezuela', 'code' => 'VE', 'alpha3' => 'VEN', 'flag_emoji' => '🇻🇪'],
            ['name' => 'Vietnam', 'code' => 'VN', 'alpha3' => 'VNM', 'flag_emoji' => '🇻🇳'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'alpha3' => 'WLF', 'flag_emoji' => '🇼🇫'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'alpha3' => 'ESH', 'flag_emoji' => '🇪🇭'],
            ['name' => 'Yemen', 'code' => 'YE', 'alpha3' => 'YEM', 'flag_emoji' => '🇾🇪'],
            ['name' => 'Zambia', 'code' => 'ZM', 'alpha3' => 'ZMB', 'flag_emoji' => '🇿🇲'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'alpha3' => 'ZWE', 'flag_emoji' => '🇿🇼'],
        ];
            
        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
